### ISSUE TITLE
Error - /bin/sh: /entrypoint.sh: not found

### ISSUE THREAD

**Issue by eddycodes** [mobidevke/mifos-docker#3]
Hi, I just tried the container and encountered an error. Please assist me with resolving the error below

/bin/sh: /entrypoint.sh: not found

**Comment by dennism501** [comment]
Hi @eddycodes by any chance are you using Windows to run docker?

**Comment by eddycodes** [comment]
Yes I am on Windows

**Comment by dennism501** [comment]
Hey, @eddycodes I had a feeling it was a windows issue. Windows uses line breaks that are different from Unix/Linux systems. So Linux uses LF and Windows uses CRLF, then when you do a `git clone` on the repo it converts the files to CRLF and dockers doesn't work well with that line break. 

So the fix is `git clone https://github.com/mobidevke/mifos-docker.git --config core.autocrlf=false`  and then run the docker installation.

**Comment by eddycodes** [comment]
Thank you so much @dennism501. Let me give it a try

**Comment by dennism501** [comment]
Let me know how it goes

**Comment by eddycodes** [comment]
Hi Dennis,

I am still getting the same error message. Please see the screenshot below

[image: image.png]

**Comment by dennism501** [comment]
Hi, @eddycodes could you walk me through the steps you are taking from the time you clone the repo to where you run. You should write the commands and show me here. Also, i am unable to see the screenshot attached

**Comment by eddycodes** [comment]
Success it's working!! I removed the containers and ran your solution. 

![image](https://user-images.githubusercontent.com/23413452/114569079-f8d85a80-9c74-11eb-82ae-e0cc9784f0e2.png)

Thanks a lot @dennism501

**Comment by dennism501** [comment]
I actually forgot about the containers, because they are built with the previous code. That's great, glad to be of help. I can close the issue now?

**Comment by eddycodes** [comment]
Sure thing
